apiVersion: v1
kind: Namespace
metadata:
  name: bigbang
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: environment-repo
  namespace: bigbang
spec:
  interval: 10m
  url: https://replace-with-your-git-repo.git
  ref:
    branch: replace-with-your-branch
  secretRef:
    name: private-git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: environment
  namespace: bigbang
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: environment-repo
  path: ./umbrella-strategy
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
